name: flutter_cupertino_settings
description: Flutter widget to create an iOS settings-table (static TableView).
version: 0.5.0
homepage: https://github.com/matthinc/flutter_cupertino_settings

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
